# Generated by Django 4.2.1 on 2023-05-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='used_coupon',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='limit',
            field=models.IntegerField(),
        ),
    ]
