# Generated by Django 4.2.1 on 2023-05-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_order_used_coupon_order_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
