# Generated by Django 4.2.1 on 2023-05-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
